import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/Navbar";
import { Montserrat } from "next/font/google";
import LoginBar from "./component/LoginBar";
import PlayButton from "./component/PlayButton";
import { PlaylistProvider } from "./context/PlaylistContext";

const montserrat = Montserrat({
  subsets : ['latin'],
  weight : ['400']
}
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <PlaylistProvider>
      <div className="w-screen h-screen bg-slate-900 text-slate-300 flex">
          <div className="w-[20%] h-[85%] ml-7 mt-7">
            <Navbar />
          </div>
          <div className="w-[80%] h-[85%] mx-7 mt-7 bg-slate-800 pt-4 px-4 rounded-lg">
            <LoginBar />
            {children}
            <div className="mb-4"></div>
          </div>
      </div>  
        <div className="absolute w-full bottom-4">
        <PlayButton />
        </div>
      </PlaylistProvider>
      
      </body>
    </html>
  );
}
